- name: Generar y transferir archivos desde Windows a Linux
  hosts: Windows
  gather_facts: false
  tasks:
   # - name: Generar archivo de estado en cada Windows
   #   ansible.windows.win_shell: |
   #    echo "Estado generado en {{ ansible_hostname }}" > C:\Temp\estado_{{ ansible_hostname }}.txt


    - name: Copiar archivo al nodo controlador
      ansible.builtin.fetch:
        src: C:\tmp\datos_estado_servidor_windows_server_2022_2.yml
        dest: /home/controlador/archivos_windows/
        flat: yes

- name: Transferir archivos al servidor Linux
  hosts: ansible_controller
  gather_facts: false
  tasks:
    - name: Copiar todos los archivos recolectados al servidor destino
      ansible.builtin.copy:
        src: /home/controlador/archivos_windows/
        dest: /home/ivera/
        owner: ivera
        group: ivera
        mode: '0644'
        remote_src: no
      become: false
      delegate_to: localhost
