- name: Generar y transferir archivos desde Windows a Linux
  hosts: windows
  gather_facts: false
  tasks:
   # - name: Generar archivo de estado en cada Windows
   #   ansible.windows.win_shell: |
   #    echo "Estado generado en {{ ansible_hostname }}" > C:\Temp\estado_{{ ansible_hostname }}.txt

    - name: Copiar archivo al nodo controlador
      ansible.builtin.fetch:
        src: C:\Temp\estado_{{ ansible_hostname }}.txt
        dest: /home/controlador/archivos_windows/
        flat: yes

- name: Transferir archivos al servidor Linux
  hosts: ansible_controller
  gather_facts: false
  tasks:
    - name: Copiar todos los archivos recolectados al servidor destino
      ansible.builtin.copy:
        src: /home/controlador/archivos_windows/
        dest: /home/ivera/reportes_windows/
        owner: ivera
        group: ivera
        mode: '0644'
        remote_src: no
      delegate_to: localhost
