- name: Ejecutar script PowerShell para SCP y enviar texto desde variable password_controller
  hosts: Windows
  gather_facts: no
  vars:
    password_controller: "Hola_123."

  tasks:
    - name: Ejecutar comando PowerShell que hace SCP y SendKeys con variable password_controller
      win_shell: |
        $wshell = New-Object -ComObject WScript.Shell

        Start-Process powershell -ArgumentList '-NoExit', '-Command', 'scp "C:\Users\usr_controller.WINDOWS-22\Documents\Estado_Servidor\datos_estado_servidor_{{ inventory_hostname }}.yml" usr_controller@192.168.100.119:/tmp/estado_servidores/' -NoNewWindow

        Start-Sleep -Seconds 2

        $wshell.SendKeys("{{ password_controller }}{ENTER}")



#    - name: Traer reporte al controlador desde Windows
#      fetch:
#        src: "{{ remote_output_dir }}\\datos_estado_servidor_{{ inventory_hostname }}.yml"
#        dest: "{{ local_output_dir }}"
#        flat: true
#      when: inventory_hostname != 'ansible_controller'
#      ignore_errors: true

#    - name: Ejecutar 'ls' en el directorio de origen
#      shell: 'ls /home/runner'
#     register: output
#      delegate_to: localhost
#     when: inventory_hostname == 'ansible_controller'
#      ignore_errors: true
