---
- name: Traer archivos desde nodos Windows al nodo controlador
  hosts: all
  gather_facts: false
  vars:
    remote_output_dir: "C:\\tmp"
    local_output_dir: "/tmp/estado_servidores/"
  tasks:
    - name: Verificar si el archivo existe en Windows
      ansible.builtin.win_shell: 'Test-Path "C:\\tmp\\reporte_{{ inventory_hostname }}.yml"'
      register: resultado

    - name: Mostrar resultado
      debug:
        var: resultado.stdout



  
#    - name: Traer reporte al controlador desde Windows
#      fetch:
#        src: "{{ remote_output_dir }}\\reporte_{{ inventory_hostname }}.yml"
#       dest: "{{ local_output_dir }}"
#       flat: true
#     ignore_errors: true
