---
- name: Traer archivos desde nodos Windows al nodo controlador
  hosts: all
  gather_facts: false
  vars:
    remote_output_dir: "C:\\tmp"
    local_output_dir: "/home/estado_servidores/"
  tasks:
    - name: Crear carpeta local en el controlador
      file:
        path: "{{ local_output_dir }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      become: false
      when: inventory_hostname == 'ansible_controller'
      ignore_errors: true

    - name: Traer reporte al controlador desde Windows
      fetch:
        src: "{{ remote_output_dir }}\\datos_estado_servidor_{{ inventory_hostname }}.yml"
        dest: "{{ local_output_dir }}"
        flat: true
      when: inventory_hostname != 'ansible_controller'
      ignore_errors: true

    - name: Ejecutar 'ls' en el directorio de origen
      shell: 'ls /home/estado_servidores/'
      register: output
      delegate_to: localhost
      become: false
      when: inventory_hostname == 'ansible_controller'
      ignore_errors: true

    - name: Copiar archivo al servidor destino
      copy:
        src: '{{ local_output_dir }}/datos_estado_servidor_{{ inventory_hostname }}.yml'
        dest: '/tmp/estado_servidores/'
      delegate_to: ansible_controller
      when: inventory_hostname == 'ansible_controller'
      ignore_errors: true
